print("wall come to rant to culcuater")
rant=int(input("enter to a rant amount"))
total_elecrity_bill=int(input("enter a total elecity bill"))
total_food_bill=int(input("enter a total food bill"))
sum=(total_elecrity_bill+total_food_bill+rant)
print(sum)
total_number_or_person=int(input("enter a total number of person"))
rant_per_person=(sum/total_number_or_person)
print(rant_per_person)